name: learning-webapi

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password 
      POSTGRES_DB: learning
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - postgres_network
    secrets:
      - postgres_password

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: kttnaiman0@gmail.com
      PGADMIN_DEFAULT_PASSWORD_FILE: /run/secrets/pgadmin_password
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - postgres_network
    depends_on:
      - postgres
    secrets:
      - pgadmin_password

  redis:
    image: redis:latest
    container_name: redis
    command: redis-server /run/secrets/redis.conf
    ports:
      - "5151:6379"
    volumes:
      - ./redis.conf:/run/secrets/redis.conf
    

volumes:
  postgres_data:
  pgadmin_data:
    
networks:
  postgres_network:
    driver: bridge

secrets:
  postgres_password: 
    file: postgres_password.env
  pgadmin_password:
    file: pgadmin_password.env